name: Scrape daily soil moisture maps

on:
  workflow_dispatch:
  schedule:
    - cron: '35 23 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Scrape soil moisture maps
      run: |-
        sh scripts/soil-moisture-anomaly-daily.sh
        sh scripts/soil-moisture-mm-daily.sh
        sh scripts/soil-moisture-percentile-daily.sh
    - name: Make animations of each type of image
      uses: jruipinto/ImageMagick-action@v1
      with: 
        command: |-
          convert -loop 0 images/*-soil-moisture-mm-daily.gif soil-moisture-mm-daily.gif
          convert -loop 0 images/*-soil-moisture-anomaly-daily.gif soil-moisture-anomaly-daily.gif
          convert -loop 0 images/*-soil-moisture-percentile-daily.gif soil-moisture-percentile-daily.gif
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add images/*.gif *.gif
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
