name: Scrape soil moisture percentile daily map

on:
  workflow_dispatch:
  schedule:
    - cron: '35 23 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Scrape soil moisture map
      run: sh scripts/soil-moisture-percentile-daily.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add images/*.gif
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
